import { IResponse } from '@app-root/shared/interfaces/http/http'

export interface ITPD {
  productId?: string
  productName?: string
}

export interface TPD {
  pdRef?: number
  coId?: string
  planId?: string
  planInsTypCd?: string
  planBusClasCd?: string
  planSuppBnftCd?: string
  planAcctTypCd?: string
  planUnitValuAmt?: number
  planUwgInd?: string
  uwgFaceAmtFct?: number
  planLocLicCd?: string
  premCalcTypCd?: string
  girPremInclInd?: string
  cntrctPremInd?: string
  sfbNegSuspInd?: string
  sfbNegSuspQty?: number
  planIssDtTypCd?: string
  planSemiAnnFct?: number
  planQtrFct?: number
  planMthlyFct?: number
  pacSemiAnnFct?: number
  planPacQtrFct?: number
  planPacMthlyFct?: number
  planPfeeAmt?: number
  planCvgPfeeAmt?: number
  semiAnnPfeeFct?: number
  planQtrPfeeFct?: number
  mthlyPfeeFct?: number
  pacSemiPfeeFct?: number
  pacQtrPfeeFct?: number
  pacMthlyPfeeFct?: number
  planIaPfeeAmt?: number
  commPlanTypCd?: string
  planCpremCalcCd?: string
  ovridFrstDgtCd?: string
  iaCommBand1Pct?: number
  iaCommBand1Amt?: number
  iaCommBand2Pct?: number
  iaCommBand2Amt?: number
  iaCommBand3Pct?: number
  iaCommBand3Amt?: number
  iaCommMaxAmt?: number
  iaIntRtId?: string
  iaIntPremId?: string
  iaIntLegalId?: string
  iaIntTaxId?: string
  planIntPayoCd?: string
  planWthdrOrdrCd?: string
  autoPremPmtInd?: string
  premRecalcOptCd?: string
  afrThrshdPeriCd?: string
  planRolovrDtInd?: string
  diaSwpThrshdCd?: string
  diaSwpThrshdAmt?: number
  planPayoMthdCd?: string
  planTxempCd?: string
  gainRptTimeCd?: string
  planTaxTypCd?: string
  planLockFndInd?: string
  iaMortUvalId?: string
  iaMortPremId?: string
  iaMortLegalId?: string
  iaMortTaxId?: string
  cvgEnhcTypCd?: string
  numGirOptQty?: string
  seGdlnApremInd?: string
  planColfndInd?: string
}

export interface TPH {
  coId?: string
  planId?: string
  appFormTypId?: string
  majLnSortCd?: string
  basicPlanInd?: string
  dbCalcTypCd?: string
  faceAmtTypCd?: string
  locGrColctId?: string
  actnColctId?: string
  planEffDt?: string
  planXpryDt?: string
  planMinMpremQty?: string
  casmId?: string
  dfltReqirId?: string
  allowCcasInd?: string
  sumInsCalcCd?: string
  ageCalcMthdCd?: string
  planAgeStbckCd?: string
  planAgeStbckQty?: string
  ageStbckStrtAge?: string
  premRenwRtCd?: string
  planModeFeeAmt?: string
  pacModeFeeAmt?: string
  lbillModeFeeAmt?: string
  commRtLoopInd?: string
  commRtTbacCd?: string
  fyrCommXtraRt?: string
  planMdrtClasCd?: string
  commTrgSstdInd?: string
  commRhSubCd?: string
  premPayUvalId?: string
  puUvalId?: string
  csvCalcMthdCd?: string
  planCsvDtTypCd?: string
  planCfTypCd?: string
  cfIntModeCd?: string
  cfIntCalcTypCd?: string
  intAdjMaxDur?: string
  csvIntRtId?: string
  pdfIntRtId?: string
  premChngDtCd?: string
  premChngAgeDur?: string
  initPremChngAge?: string
  ultPremChngAge?: string
  xpryDtCalcCd?: string
  polXpryAgeDur?: string
  planBaseXpryAge?: string
  cvgXpryAgeDur?: string
  planCvgXpryAge?: string
  matDtCalcCd?: string
  planMatAgeDur?: string
  planMatAge?: string
  planDurTypCd?: string
  cnvrXpryDtCd?: string
  cnvrXpryAgeDur?: string
  planAdbXpryAge?: string
  planWpXpryAge?: string
  planWpXpryCd?: string
  redcEpXpryAge?: string
  ownOccpXpryAge?: string
  planLtaXpryAge?: string
  planLtbXpryAge?: string
  pdisabXpryAge?: string
  planColaXpryAge?: string
  nfPrcesMoDur?: string
  nfPrcesDyDur?: string
  rpuTbacId?: string
  fpuPlanBaseId?: string
  etiFaceCalcCd?: string
  etiTbacId?: string
  notiDtCalcCd?: string
  notiLowAgeDur?: string
  notiHighAgeDur?: string
  planNotiReasnCd?: string
  notiDeptId?: string
  trmPremRfndRt?: string
  loanIntCalcCd?: string
  loanIntRtTypCd?: string
  planLoanIntRt?: string
  loanIntRtId?: string
  aplIntRtId?: string
  colfndReqirInd?: string
  planCvgLoanInd?: string
  planParCd?: string
  dodIntRtId?: string
  divOytTbacId?: string
  divPuaTbacId?: string
  puaDivCalcCd?: string
  planRpuDivRt?: string
  planDivIntRtId?: string
  planBonIntRtId?: string
  planBonEffMo?: string
  planBonEffDy?: string
  planVpoInd?: string
  iswlFrstCalcDur?: string
  iswlCalcFreqDur?: string
  iswlCalcAdvDur?: string
  iswlPremVarRt?: string
  afrThrshdCd?: string
  dirDposMinAmt?: string
  pacDposMinAmt?: string
  minCaslPayoAmt?: string
  planGuarIntRt?: string
  acumBrkptAmt?: string
  planRolovrTypCd?: string
  minRolovrMoDur?: string
  minRolovrDyDur?: string
  maxRolovrMoDur?: string
  maxRolovrDyDur?: string
  planAdminFeeAmt?: string
  adminFeeWavAmt?: string
  planMktvalAdjCd?: string
  matChrgRtbl2Id?: string
  mnpmtTrgSstdInd?: string
  pmtLoadOrdrCd?: string
  pmtLoadRtbl2Id?: string
  pmtLoadFlatAmt?: string
  pmtLoadCalcCd?: string
  pmtLoadSstdInd?: string
  pmtAllocMthdCd?: string
  fpulAddlPremInd?: string
  fpulLoadTypCd?: string
  psurChrgTypCd?: string
  psurChrgFlatAmt?: string
  psurChrgRtbl2Id?: string
  surrChrgTypCd?: string
  surrChrgCalcCd?: string
  surrChrgFlatAmt?: string
  surrChrgRtbl2Id?: string
  planSurrChrgCd?: string
  surrTrgSstdInd?: string
  surrAdjCalcCd?: string
  surrAdjMoDur?: string
  surrAdjTypCd?: string
  dposWthdrOrdrCd?: string
  cvAllocMthdCd?: string
  cvgCvAllocInd?: string
  planNarDscntRt?: string
  planImprdRtCd?: string
  planImprdIntRt?: string
  planRegInd?: string
  t5RegTitlTxt?: string
  planTaxwhInd?: string
  pnsnQualfInd?: string
  dispWthdrOrdrCd?: string
  xempTstUvalId?: string
  planTamraInd?: string
  planTamraMxdxId?: string
  plan7702MxdxId?: string
  planRsrvCalcCd?: string
  valnLblId?: string
  adbPlanId?: string
  wpPlanId?: string
  redcEpPlanId?: string
  ownOccpPlanId?: string
  ltaPlanId?: string
  ltbPlanId?: string
  pdisabPlanId?: string
  cola1PlanId?: string
  cola2PlanId?: string
  cola3PlanId?: string
  cola4PlanId?: string
  applId?: string
  enhcFreqDur?: string
  enhcStrtDur?: string
  enhcEndDur?: string
  enhcEndAge?: string
  enhcUwgFreqDur?: string
  enhcNelctDur?: string
  enhcHiatusDur?: string
  periStmtTypCd?: string
  periStmtMoDur?: string
  periStmtDyDur?: string
  indxIncrMthdCd?: string
  indxIncrMoDur?: string
  indxIncrDyDur?: string
  mcvCalcReqirInd?: string
  mcvIntMthdCd?: string
  mcvPmtLoadCd?: string
  planEicFreqCd?: string
  eicInitYrDur?: string
  eicSubseqYrDur?: string
  freeLkPrcesInd?: string
  freeLkIncrCd?: string
  mortXpnsChrgAge?: string
  mortXpnsChrgDur?: string
  mortXpnsCalcCd?: string
  trailCommFreqCd?: string
  trailCommBegDur?: string
  trailCommLagDur?: string
  ssPremCalcCd?: string
  rpuEtiCd?: string
  etiCsvProcCd?: string
  reinstIntRtId?: string
  divPlus6Acct?: string
}

export interface Data {
  tpd?: TPD[]
  tph?: TPH[]
}

export interface IResPlanHeaderItem extends IResponse<Data> {}

export module IProductPlanHeader {
  export interface IPlanHeaderItem extends IResponse<Data> {}
}
