// module.exports = function(app) {
//   var selectChannel = require('../controller/selectChannel-ctrl');
//   app.get('/api/select-channel/distribution-channel', selectChannel.distributionChannel);
//   app.get('/api/select-channel/channel-sale-group', selectChannel.channelSaleGroup);
//   app.get('/api/select-channel/internal-company', selectChannel.internalCompany);
//   // app.get('/api/testRefer', selectChannel.testAdd);
//   app.post('/api/save-draft', selectChannel.saveDraft);
  
// };


// const config = require('../config/config').get(process.env.NODE_ENV).prefix_api;
const express = require('express');
const selectChannelCtrl = require('../controller/selectChannel-ctrl');
var router = express.Router();
router.route('/select-channel').get(selectChannelCtrl.selectChannel);
module.exports = router;


// C0000000001
// Supphasan Rangsan branch

// {
//  "resultCode" : "20000",
//  "resultDescription" : "Success",
//  "resultData" : [{
//    "abbrev_data" : "SPR",
//    "busRegistration_data" : "2098765342098",
//    "chnSalesCode_key4" : "TW",
//    "closingHourFri_data" : "20:00:00",
//    "closingHourMon_data" : "20:00:00",
//    "closingHourSat_data" : "20:00:00",
//    "closingHourSun_data" : "",
//    "closingHourThu_data" : "20:00:00",
//    "closingHourTue_data" : "20:00:00",
//    "closingHourWed_data" : "20:00:00",
//    "companyId_key1" : "C0000000001",
//    "createdBy_data" : "SUWAREEK",
//    "created_data" : "20160909153300+0700",
//    "distChnCode_key3" : "TL",
//    "effectiveDt_data" : "20160909153300+0700",
//    "idNo_data" : "2098765342098",
//    "idType_data" : "",
//    "isOpenSat_data" : "Y",
//    "isOpeningFri_data" : "Y",
//    "isOpeningMon_data" : "Y",
//    "isOpeningSun_data" : "Y",
//    "isOpeningThu_data" : "Y",
//    "isOpeningTue_data" : "Y",
//    "isOpeningWed_data" : "Y",
//    "lastUpdBy_data" : "SUWAREEK",
//    "lastUpd_data" : "20160909153300+0700",
//    "licenseCode_key2" : "1000008",
//    "locationCode_key0" : "293840",
//    "locationIdForSB_data" : "U0000000001",
//    "modificationNum_data" : "1",
//    "nameEn_data" : "Supphasan Rangsan branch",
//    "nameTh_data" : "สาขา ศุภสารรังสรรค์",
//    "openingHourFri_data" : "10:00:00",
//    "openingHourMon_data" : "10:00:00",
//    "openingHourSat_data" : "10:00:00",
//    "openingHourSun_data" : "10:00:00",
//    "openingHourThu_data" : "10:00:00",
//    "openingHourTue_data" : "10:00:00",
//    "openingHourWed_data" : "10:00:00",
//    "paymentChnStatus_data" : "ACTIVE",
//    "paymentChn_data" : "2",
//    "remark_data" : "",
//    "renovateFlag_data" : "",
//    "rowIdSB_data" : "1-10BAB",
//    "shopArea_data" : "PLAZA",
//    "shopClass_data" : "TWZ_PLUS",
//    "shopSegment_data" : "",
//    "shopType_data" : "",
//    "status_data" : "ACTIVE",
//    "terminateDt_data" : "",
//    "vatBranchName_data" : "",
//    "vatBranchNo_data" : "00000",
//    "vatType_data" : "NONVAT",
//    "wtAddress_data" : "",
//    "wtName_data" : ""
//   }, {
//    "abbrev_data" : "SPR",
//    "busRegistration_data" : "2098765342098",
//    "chnSalesCode_key4" : "TW",
//    "closingHourFri_data" : "20:00:00",
//    "closingHourMon_data" : "20:00:00",
//    "closingHourSat_data" : "20:00:00",
//    "closingHourSun_data" : "",
//    "closingHourThu_data" : "20:00:00",
//    "closingHourTue_data" : "20:00:00",
//    "closingHourWed_data" : "20:00:00",
//    "companyId_key1" : "C0000000001",
//    "createdBy_data" : "SUWAREEK",
//    "created_data" : "20160909153300+0700",
//    "distChnCode_key3" : "TL",
//    "effectiveDt_data" : "20160909153300+0700",
//    "idNo_data" : "2098765342098",
//    "idType_data" : "",
//    "isOpenSat_data" : "Y",
//    "isOpeningFri_data" : "Y",
//    "isOpeningMon_data" : "Y",
//    "isOpeningSun_data" : "Y",
//    "isOpeningThu_data" : "Y",
//    "isOpeningTue_data" : "Y",
//    "isOpeningWed_data" : "Y",
//    "lastUpdBy_data" : "SUWAREEK",
//    "lastUpd_data" : "20160909153300+0700",
//    "licenseCode_key2" : "1000008",
//    "locationCode_key0" : "2938400000",
//    "locationIdForSB_data" : "U0000000001",
//    "modificationNum_data" : "1",
//    "nameEn_data" : "Supphasan Rangsan branch",
//    "nameTh_data" : "สาขา ศุภสารรังสรรค์",
//    "openingHourFri_data" : "10:00:00",
//    "openingHourMon_data" : "10:00:00",
//    "openingHourSat_data" : "10:00:00",
//    "openingHourSun_data" : "10:00:00",
//    "openingHourThu_data" : "10:00:00",
//    "openingHourTue_data" : "10:00:00",
//    "openingHourWed_data" : "10:00:00",
//    "paymentChnStatus_data" : "ACTIVE",
//    "paymentChn_data" : "2",
//    "remark_data" : "",
//    "renovateFlag_data" : "",
//    "rowIdSB_data" : "1-10BAB",
//    "shopArea_data" : "PLAZA",
//    "shopClass_data" : "TWZ_PLUS",
//    "shopSegment_data" : "",
//    "shopType_data" : "",
//    "status_data" : "ACTIVE",
//    "terminateDt_data" : "",
//    "vatBranchName_data" : "",
//    "vatBranchNo_data" : "00000",
//    "vatType_data" : "NONVAT",
//    "wtAddress_data" : "",
//    "wtName_data" : ""
//   }, {
//    "abbrev_data" : "aaSPR",
//    "busRegistration_data" : "2098765342098",
//    "chnSalesCode_key4" : "TW",
//    "closingHourFri_data" : "20:00:00",
//    "closingHourMon_data" : "20:00:00",
//    "closingHourSat_data" : "20:00:00",
//    "closingHourSun_data" : "20:00:00",
//    "closingHourThu_data" : "20:00:00",
//    "closingHourTue_data" : "20:00:00",
//    "closingHourWed_data" : "20:00:00",
//    "companyId_key1" : "C0000000001",
//    "createdBy_data" : "SUWAREEK",
//    "created_data" : "20160909153300+0700",
//    "distChnCode_key3" : "TL",
//    "effectiveDt_data" : "20160909153300+0700",
//    "idNo_data" : "2098765342098",
//    "idType_data" : "",
//    "isOpenSat_data" : "Y",
//    "isOpeningFri_data" : "Y",
//    "isOpeningMon_data" : "Y",
//    "isOpeningSun_data" : "Y",
//    "isOpeningThu_data" : "Y",
//    "isOpeningTue_data" : "Y",
//    "isOpeningWed_data" : "Y",
//    "lastUpdBy_data" : "SUWAREEK",
//    "lastUpd_data" : "20160909153300+0700",
//    "licenseCode_key2" : "1000008",
//    "locationCode_key0" : "29293840",
//    "locationIdForSB_data" : "U0000000001",
//    "modificationNum_data" : "1",
//    "nameEn_data" : "Supphasan Rangsan branch",
//    "nameTh_data" : "สาขา ศุภสารรังสรรค์",
//    "openingHourFri_data" : "10:00:00",
//    "openingHourMon_data" : "10:00:00",
//    "openingHourSat_data" : "10:00:00",
//    "openingHourSun_data" : "10:00:00",
//    "openingHourThu_data" : "10:00:00",
//    "openingHourTue_data" : "10:00:00",
//    "openingHourWed_data" : "10:00:00",
//    "paymentChnStatus_data" : "ACTIVE",
//    "paymentChn_data" : "2",
//    "remark_data" : "",
//    "renovateFlag_data" : "",
//    "rowIdSB_data" : "1-10BAB",
//    "shopArea_data" : "PLAZA",
//    "shopClass_data" : "TWZ_PLUS",
//    "shopSegment_data" : "",
//    "shopType_data" : "",
//    "status_data" : "ACTIVE",
//    "terminateDt_data" : "",
//    "vatBranchName_data" : "",
//    "vatBranchNo_data" : "00000",
//    "vatType_data" : "NONVAT",
//    "wtAddress_data" : "",
//    "wtName_data" : ""
//   }, {
//    "abbrev_data" : "",
//    "busRegistration_data" : "2098765342098",
//    "chnSalesCode_key4" : "TW",
//    "closingHourFri_data" : "20:00:00",
//    "closingHourMon_data" : "20:00:00",
//    "closingHourSat_data" : "20:00:00",
//    "closingHourSun_data" : "20:00:00",
//    "closingHourThu_data" : "20:00:00",
//    "closingHourTue_data" : "20:00:00",
//    "closingHourWed_data" : "20:00:00",
//    "companyId_key1" : "C0000000001",
//    "createdBy_data" : "SUWAREEK",
//    "created_data" : "20160909153300+0700",
//    "distChnCode_key3" : "TL",
//    "effectiveDt_data" : "20160909153300+0700",
//    "idNo_data" : "2098765342098",
//    "idType_data" : "TAX_ID",
//    "isOpenSat_data" : "Y",
//    "isOpeningFri_data" : "Y",
//    "isOpeningMon_data" : "Y",
//    "isOpeningSun_data" : "Y",
//    "isOpeningThu_data" : "Y",
//    "isOpeningTue_data" : "Y",
//    "isOpeningWed_data" : "Y",
//    "lastUpdBy_data" : "SUWAREEK",
//    "lastUpd_data" : "20160909153300+0700",
//    "licenseCode_key2" : "1000008",
//    "locationCode_key0" : "U0000000002",
//    "locationIdForSB_data" : "U0000000001",
//    "modificationNum_data" : "",
//    "nameEn_data" : "",
//    "nameTh_data" : "",
//    "openingHourFri_data" : "10:00:00",
//    "openingHourMon_data" : "10:00:00",
//    "openingHourSat_data" : "10:00:00",
//    "openingHourSun_data" : "10:00:00",
//    "openingHourThu_data" : "10:00:00",
//    "openingHourTue_data" : "10:00:00",
//    "openingHourWed_data" : "10:00:00",
//    "paymentChnStatus_data" : "ACTIVE",
//    "paymentChn_data" : "2",
//    "remark_data" : "",
//    "renovateFlag_data" : "",
//    "rowIdSB_data" : "1-10BAB",
//    "shopArea_data" : "PLAZA",
//    "shopClass_data" : "",
//    "shopSegment_data" : "",
//    "shopType_data" : "",
//    "status_data" : "ACTIVE",
//    "terminateDt_data" : "",
//    "vatBranchName_data" : " สำนักงานใหญ่",
//    "vatBranchNo_data" : "00000",
//    "vatType_data" : "NONVAT",
//    "wtAddress_data" : "",
//    "wtName_data" : ""
//   }
//  ]
// }