import { Component, OnInit } from '@angular/core'
import { MenuItem } from 'primeng/api'
import { IProductPlanHeader, TPD, TPH } from '../../interface/TPD'

@Component({
  selector: 'app-plan-header',
  templateUrl: './plan-header.component.html',
  styleUrls: ['./plan-header.component.scss'],
})
export class PlanHeaderComponent implements OnInit {
  product: TPH[]
  items: MenuItem[]
  activeItem: MenuItem
  displayModal = false
  collapse = true

  constructor() {}

  ngOnInit(): void {
    this.getProduct()
    this.items = [
      { label: 'Home', icon: 'pi pi-fw pi-home' },
      { label: 'Calendar', icon: 'pi pi-fw pi-calendar' },
    ]
    this.activeItem = this.items[0]
  }

  getProduct() {
    const data = {
      status: 200,
      success: true,
      message: '',
      errorCode: null,
      data: {
        tpd: [
          {
            pdRef: 2,
            coId: 'CP',
            planId: '**RPUB',
            planInsTypCd: '8',
            planBusClasCd: 'L',
            planSuppBnftCd: 'N',
            planAcctTypCd: '1',
            planUnitValuAmt: 1000,
            planUwgInd: 'Y',
            uwgFaceAmtFct: 1.0,
            planLocLicCd: 'A',
            premCalcTypCd: 'N',
            girPremInclInd: 'N',
            cntrctPremInd: 'Y',
            sfbNegSuspInd: 'N',
            sfbNegSuspQty: 0,
            planIssDtTypCd: 'E',
            planSemiAnnFct: 0.51,
            planQtrFct: 0.26,
            planMthlyFct: 0.09,
            pacSemiAnnFct: 0.51,
            planPacQtrFct: 0.26,
            planPacMthlyFct: 0.09,
            planPfeeAmt: 0.0,
            planCvgPfeeAmt: 0.0,
            semiAnnPfeeFct: 0.51,
            planQtrPfeeFct: 0.26,
            mthlyPfeeFct: 0.09,
            pacSemiPfeeFct: 0.51,
            pacQtrPfeeFct: 0.26,
            pacMthlyPfeeFct: 0.09,
            planIaPfeeAmt: 250.0,
            commPlanTypCd: 'L0',
            planCpremCalcCd: '0',
            ovridFrstDgtCd: '0',
            iaCommBand1Pct: 2.0,
            iaCommBand1Amt: 100000.0,
            iaCommBand2Pct: 2.0,
            iaCommBand2Amt: 100000.0,
            iaCommBand3Pct: 2.0,
            iaCommBand3Amt: 1000000000.0,
            iaCommMaxAmt: 2000.0,
            iaIntRtId: '     ',
            iaIntPremId: ' ',
            iaIntLegalId: ' ',
            iaIntTaxId: ' ',
            planIntPayoCd: 'N/A',
            planWthdrOrdrCd: 'N',
            autoPremPmtInd: 'N',
            premRecalcOptCd: 'N',
            afrThrshdPeriCd: 'N',
            planRolovrDtInd: 'N',
            diaSwpThrshdCd: 'N',
            diaSwpThrshdAmt: 0.0,
            planPayoMthdCd: 'C',
            planTxempCd: 'N',
            gainRptTimeCd: 'Y',
            planTaxTypCd: '9',
            planLockFndInd: 'N',
            iaMortUvalId: '     ',
            iaMortPremId: ' ',
            iaMortLegalId: ' ',
            iaMortTaxId: ' ',
            cvgEnhcTypCd: 'N',
            numGirOptQty: '0',
            seGdlnApremInd: 'N',
            planColfndInd: 'N',
          },
        ],
        tph: [
          {
            coId: 'CP',
            planId: '**RPUB',
            appFormTypId: 'W',
            majLnSortCd: '1',
            basicPlanInd: 'Y',
            dbCalcTypCd: 'S',
            faceAmtTypCd: 'D',
            locGrColctId: 'LOCAT',
            actnColctId: 'ACTTR',
            planEffDt: '1940-01-01',
            planXpryDt: '',
            planMinMpremQty: '1',
            casmId: 'TPAS1',
            dfltReqirId: 'TPAGE',
            allowCcasInd: 'Y',
            sumInsCalcCd: '0',
            ageCalcMthdCd: '1',
            planAgeStbckCd: 'N',
            planAgeStbckQty: '0',
            ageStbckStrtAge: '0',
            premRenwRtCd: 'N',
            planModeFeeAmt: '0',
            pacModeFeeAmt: '0',
            lbillModeFeeAmt: '0',
            commRtLoopInd: 'N',
            commRtTbacCd: 'R',
            fyrCommXtraRt: '0',
            planMdrtClasCd: 'Z',
            commTrgSstdInd: 'N',
            commRhSubCd: 'CO14',
            premPayUvalId: 'NO',
            puUvalId: 'NO',
            csvCalcMthdCd: 'N',
            planCsvDtTypCd: 'P',
            planCfTypCd: 'N',
            cfIntModeCd: 'NO',
            cfIntCalcTypCd: 'N',
            intAdjMaxDur: '2',
            csvIntRtId: 'OT78A1',
            pdfIntRtId: 'IR03',
            premChngDtCd: '0',
            premChngAgeDur: '0',
            initPremChngAge: '0',
            ultPremChngAge: '0',
            xpryDtCalcCd: '0',
            polXpryAgeDur: '0',
            planBaseXpryAge: '0',
            cvgXpryAgeDur: '0',
            planCvgXpryAge: '0',
            matDtCalcCd: 'A',
            planMatAgeDur: '90',
            planMatAge: '0',
            planDurTypCd: 'N',
            cnvrXpryDtCd: 'N',
            cnvrXpryAgeDur: '0',
            planAdbXpryAge: '0',
            planWpXpryAge: '0',
            planWpXpryCd: 'N',
            redcEpXpryAge: '0',
            ownOccpXpryAge: '0',
            planLtaXpryAge: '0',
            planLtbXpryAge: '0',
            pdisabXpryAge: '0',
            planColaXpryAge: '0',
            nfPrcesMoDur: '0',
            nfPrcesDyDur: '45',
            rpuTbacId: '**RPU',
            fpuPlanBaseId: '',
            etiFaceCalcCd: '1',
            etiTbacId: 'NO',
            notiDtCalcCd: '0',
            notiLowAgeDur: '0',
            notiHighAgeDur: '0',
            planNotiReasnCd: '',
            notiDeptId: 'NO',
            trmPremRfndRt: '1',
            loanIntCalcCd: '1',
            loanIntRtTypCd: 'F',
            planLoanIntRt: '0.08',
            loanIntRtId: 'IR01',
            aplIntRtId: 'IR01',
            colfndReqirInd: 'N',
            planCvgLoanInd: 'Y',
            planParCd: '0',
            dodIntRtId: '',
            divOytTbacId: 'NO',
            divPuaTbacId: 'NO',
            puaDivCalcCd: 'P',
            planRpuDivRt: '0',
            planDivIntRtId: '',
            planBonIntRtId: '',
            planBonEffMo: '12',
            planBonEffDy: '31',
            planVpoInd: 'N',
            iswlFrstCalcDur: '5',
            iswlCalcFreqDur: '5',
            iswlCalcAdvDur: '60',
            iswlPremVarRt: '0.1',
            afrThrshdCd: 'N',
            dirDposMinAmt: '0',
            pacDposMinAmt: '0',
            minCaslPayoAmt: '0',
            planGuarIntRt: '0',
            acumBrkptAmt: '0',
            planRolovrTypCd: 'N',
            minRolovrMoDur: '0',
            minRolovrDyDur: '0',
            maxRolovrMoDur: '0',
            maxRolovrDyDur: '0',
            planAdminFeeAmt: '0',
            adminFeeWavAmt: '0',
            planMktvalAdjCd: 'N',
            matChrgRtbl2Id: 'NO',
            mnpmtTrgSstdInd: 'N',
            pmtLoadOrdrCd: 'N',
            pmtLoadRtbl2Id: 'NONE',
            pmtLoadFlatAmt: '0',
            pmtLoadCalcCd: 'N',
            pmtLoadSstdInd: 'N',
            pmtAllocMthdCd: 'N',
            fpulAddlPremInd: 'N',
            fpulLoadTypCd: 'E',
            psurChrgTypCd: 'N',
            psurChrgFlatAmt: '0',
            psurChrgRtbl2Id: 'NO',
            surrChrgTypCd: 'N',
            surrChrgCalcCd: 'N',
            surrChrgFlatAmt: '0',
            surrChrgRtbl2Id: 'NO',
            planSurrChrgCd: 'N',
            surrTrgSstdInd: 'N',
            surrAdjCalcCd: 'N',
            surrAdjMoDur: '0',
            surrAdjTypCd: 'N',
            dposWthdrOrdrCd: 'N/A',
            cvAllocMthdCd: 'N',
            cvgCvAllocInd: 'Y',
            planNarDscntRt: '1',
            planImprdRtCd: 'N',
            planImprdIntRt: '0',
            planRegInd: 'N',
            t5RegTitlTxt: 'RSP-128-4-P-1',
            planTaxwhInd: 'N',
            pnsnQualfInd: 'N',
            dispWthdrOrdrCd: '4',
            xempTstUvalId: '',
            planTamraInd: 'N',
            planTamraMxdxId: '',
            plan7702MxdxId: '',
            planRsrvCalcCd: '',
            valnLblId: '',
            adbPlanId: 'NO',
            wpPlanId: 'NO',
            redcEpPlanId: 'NO',
            ownOccpPlanId: 'NO',
            ltaPlanId: 'NO',
            ltbPlanId: 'NO',
            pdisabPlanId: 'NO',
            cola1PlanId: 'NO',
            cola2PlanId: 'NO',
            cola3PlanId: 'NO',
            cola4PlanId: 'NO',
            applId: '1',
            enhcFreqDur: '1',
            enhcStrtDur: '1',
            enhcEndDur: '0',
            enhcEndAge: '0',
            enhcUwgFreqDur: '2',
            enhcNelctDur: '2',
            enhcHiatusDur: '2',
            periStmtTypCd: 'N',
            periStmtMoDur: '0',
            periStmtDyDur: '0',
            indxIncrMthdCd: 'N',
            indxIncrMoDur: '0',
            indxIncrDyDur: '0',
            mcvCalcReqirInd: 'N',
            mcvIntMthdCd: 'N',
            mcvPmtLoadCd: 'N',
            planEicFreqCd: 'N',
            eicInitYrDur: '0',
            eicSubseqYrDur: '0',
            freeLkPrcesInd: 'N',
            freeLkIncrCd: 'N',
            mortXpnsChrgAge: '0',
            mortXpnsChrgDur: '0',
            mortXpnsCalcCd: 'N',
            trailCommFreqCd: 'N',
            trailCommBegDur: '0',
            trailCommLagDur: '0',
            ssPremCalcCd: 'T',
            rpuEtiCd: 'A',
            etiCsvProcCd: '',
            reinstIntRtId: 'IR01',
            divPlus6Acct: '',
          },
        ],
      },
      error: null,
    }

    this.product = data.data.tph
  }

  onDetail() {
    this.displayModal = true
  }
}
